# Generated by Django 4.2.9 on 2024-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_modified",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
